import React, { useState } from 'react'
import Card from '../components/Card'
import FormField from '../components/FormField'
import Loader from '../components/Loader'

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post.id} {...post} />)
  }

  return (
    <h2 className='text-xl font-bold mt-5 text-blue-500'>{title}</h2>
  )
}

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPost, setAllPost] = useState(null);
  const [searchText, setSearchText] = useState('');
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-3xl text-gray-800'>Community Showcase</h1>
        <p className='text-base text-gray-500 max-w-[500px] mt-2'>
          Browse through the collection of imaginative and stunning images generated by the Imagery.
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='mb-3 text-xl font-medium text-gray-500'>
                Showing results for <span className='text-gray-800'>{searchText}</span>
              </h2>
            )}
            <div className='grid grid-cols-1 xs:grid-cols-2 sm:grid-cols-3 lg:grid-cols-4'>
              {searchText ? (
                <RenderCards data={searchedResult} title='No results found' />
              ) : (
                <RenderCards data={allPost} title='No posts to show' />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Home